#Configuration

db_information:
  user_name: "neo4j"
  password: "neo4j_is_nice"
  host: 172.17.0.1  #local host for docker

#Groups available
groups: 
  group_names: ["Broward County","Palm Beach County","Broward and Palm Beach Counties","Florida State Providers"]
